org: aphexlog
app: merdok
service: merdok

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  websocketsApiName: ${self:service}-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action
  websocketsDescription: Custom Serverless Websockets
  environment:
    DYNAMODB_CONVERSATIONS_TABLE_NAME: ${self:service}-${self:provider.stage}-conversations
    DYNAMODB_WEBSOCKET_TABLE_NAME: ${self:service}-${self:provider.stage}-websockets
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - !GetAtt ConversationsTable.Arn
        - !GetAtt WebsocketConnectionsTable.Arn

custom:
  DOMAIN_NAME: elevator-robot.com
  client:
  # bucketName should be the domain name of your website
    bucketName: ${self:custom.DOMAIN_NAME}
    distributionFolder: client/public
  pythonRequirements:
    layer: true
    fileName: api/requirements.txt

package:
  individually: true
  include:
    - "api/"
  exclude:
    - "node_modules/**"
    - "test/**"
    - ".git/**"
    - ".serverless/**"
    - ".venv/**"
    - "serverless_sdk/**"
    - "client/**"
    - "package-lock.json"
    - "package.json"
    - "README.md"

functions:
  connect:
    handler: api/handler.connect
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: api/handler.disconnect
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - websocket:
          route: $disconnect
  sendMessage:
    handler: api/handler.send_message
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - websocket:
          route: sendMessage


resources:
  Resources:
    ConversationsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: conversationId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: conversationId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_CONVERSATIONS_TABLE_NAME}
    WebsocketConnectionsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:service}-${self:provider.stage}-websockets
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: False
            RequireNumbers: False
            RequireSymbols: False
            RequireUppercase: False
        Schema:
          - AttributeDataType: String
            Name: email
            Required: true
          - AttributeDataType: String
            Name: name
            Required: true

plugins:
  - serverless-python-requirements
