org: aphexlog
app: merdok
service: merdok

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.DYNAMODB_TABLE_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: !GetAtt ConversationsTable.Arn

custom:
  DYNAMODB_TABLE_NAME: ${self:service}-${opt:stage, self:provider.stage}
  DOMAIN_NAME: elevator-robot.com
  client:
    bucketName: ${self:custom.DOMAIN_NAME}
    distributionFolder: client/public

package:
  individually: true
  include:
    - "lambdas/"
    - "!*/**" # TODO: this fixes an issue .. look into it
  exclude:
    - "node_modules/**"
    - "test/**"
    - ".git/**"
    - ".serverless/**"
    - ".venv/**"
    - "serverless_sdk/**"

functions:
  connect:
    handler: lambdas/handler.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: lambdas/handler.disconnect
    events:
      - websocket:
          route: $disconnect
  sendMessage:
    handler: lambdas/handler.sendMessage
    events:
      - websocket:
          route: sendMessage

resources:
  Resources:
    ConversationsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: conversationId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: conversationId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.DYNAMODB_TABLE_NAME}
    # ElevatorRobotRecordSet:
    #   Type: "AWS::Route53::RecordSet"
    #   Properties: 
    #     HostedZoneName: "${self:custom.DOMAIN_NAME}."
    #     Name: "${self:custom.DOMAIN_NAME}."
    #     Type: A
    #     AliasTarget:
    #       HostedZoneId: "Z0809465328WIUFUDSAKZ"
    #       DNSName:  "s3-website-us-east-1.amazonaws.com"

plugins:
  - serverless-python-requirements
  - serverless-finch
