import Head from "next/head";
import LoginWindow from './componants/LoginWindow'
import Chat from './componants/Chat'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* create a login window in the center of the screen */}
      <Chat />
      </>
  );
}